version: '3'

services:
  # Laravel application
  app:
    build: ./php
    container_name: laravel-app
    working_dir: /var/www/html
    restart: unless-stopped
    volumes :
      - ./laravel:/var/www/html
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - laravel-network
    depends_on:
      - db

  # Nginx web server
  webserver:
    image: nginx:latest
    container_name: laravel-webserver
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - laravel-network

  # MySQL database
  db:
    image: mysql:latest
    container_name: laravel-mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./mysql/.env
    ports:
      - "3306:3306"
    networks:
      - laravel-network

  # Adminer for database management
  adminer:
    image: adminer
    container_name: laravel-adminer
    ports:
      - "8081:8080"
    networks:
      - laravel-network
    depends_on:
      - db

networks:
  laravel-network:
    driver: bridge
