version: '3'

services:
  # Laravel application
  app:
    image: php:8.2-fpm
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - db
    command: bash -c "apt-get update && apt-get install -y git zip unzip && docker-php-ext-install pdo_mysql && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && php-fpm"

  # Nginx web server
  webserver:
    image: nginx:latest
    container_name: laravel-webserver
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - laravel-network

  # MySQL database
  db:
    image: mysql:latest
    container_name: laravel-mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./mysql/.env
    ports:
      - "3306:3306"
    networks:
      - laravel-network

  # Adminer for database management
  adminer:
    image: adminer
    container_name: laravel-adminer
    ports:
      - "8081:8080"
    networks:
      - laravel-network
    depends_on:
      - db

networks:
  laravel-network:
    driver: bridge
